version="0.3.2"

[scripts]
## Builds Tailwind CSS for development (no purging)
build-tailwind-dev = [
    "cd tools/tailwind-yew-builder",
    "INPUT=../../config/ SOURCE_CODE=../../ docker compose up dev"
]

## Builds Tailwind CSS for production (maximum purging and minification)
build-tailwind-prod = [
    "cd tools/tailwind-yew-builder",
    "INPUT=../../config/ SOURCE_CODE=../../ docker compose up prod"
]

## Builds Tailwind CSS for development usage
setup.subcommands.tailwind = "bonnie build-tailwind-dev"
setup.subcommands.prompt-tailwind = "echo \"Install tailwind-yew-builder with git submodule update --init --recursive\""
setup.order = """
tailwind {
    Failure => prompt-tailwind
}
"""

## Builds everything
build.cmd = "cargo build"

## Builds the frontend
build.subcommands.frontend = [
    "bonnie build-tailwind-prod",
    "cargo build"
]

## Runs the frontend, watching for changes (uses Trunk)
## Tailwind is assumed to be set up after `setup`
run.subcommands.frontend = [
    "trunk serve"
]
