[package]
name = "geoffjay-github-io"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
wasm-logger = "0.2"
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
